### ISSUE TITLE
Nová verze tiskárny

### ISSUE THREAD

**Issue by roman-dvorak** [MLAB-project/RebeliX#16]
Protože se stávající tiskárnou je řada problémů, zde je návrh, jak tyto problémy vyřešit drobnou změnou její konstrukce.

### Závitové šruby místo řemenů
Na všech osách pro pohyb použít helixové tyče [DrySpin](https://www.igus.cz/product/895) se závitem Ds6,35x25,4. Tento závit má velmi podobné rozlišení jako aktuální řešení GT2 řemenů.  Přínos této změny by měl být ve skoro nulovém back-slashi a nulové pružnosti. Na všech osách bude stačit pouze jeden motor

### Lineární ložiska
Místo lineárních kuličkových ložisek použít IGUS plastová ložiska. Zde je potřeba, aby všechny ložisková pouzdra byla okolo ložiska ze všech stran a nedocházelo k jeho mechanické deformaci. Tím přestane správně fungovat. V úplně ideálním případě použít i IGUS vodící tyče - ale klasická leštěná ocelová tyč by měla být dostatečná.

### HotEnd
Použít originální HotEnd E3D V6.

Na konci HE je teflonová trubička (která je vždy ve studené části HE). Tuto trubičku lze použít jako vedení filamentu přímo od podávacího kolečka. To by mělo minimalizovat počet možných hran cestou od kolečka do trysky.

### Extruder
Navrhnout úplně jiný extruder, který bude mít přímé podávání filamentu (bez obrovského převodového kola) Také je potřeba, aby podávací motor byl co nejblíže konci hotendu. To lze vyřešit několika způsoby.

Buď bude motor umístěn směrem dopředu. Což je možnost, která se mi nejméně líbí, protože vytváří sílu na osu Y. 

Motor bude umístěn mezi vodícími tyčemi osy Y. Jeho šroub bude ještě pod nebo nad motorem. 

Motor s prodluženou osou (cca 4 cm)  - motor může být přidělán ze zadní strany. Těsně za vodícími tyčemi. Tím se přesune těžiště tiskové hlavy co nejblíže středu osy Y. Popř. by osa motoru mohla být prodloužena nějakým vysoustruženým adaptérem umístených na dvou ložiskách.

Extruder by měl býť snadno vyměnitelný popřípadě alespoň servisovatelný.

Senzor přítomnosti filamentu nebo dokonce jeho pohybu.

### Přítlačné kolečko
Použít přítlačné kolečko [BondTech](https://www.bondtech.se/en/product/drivegear-kits/).

### Senzor výšky podložky
Docela fajn mi příjde BLtouch (originální) Funguje spolehlivě pokud má kvalitní 5V napájení. 
Další možnost je použít kapacitní nebo jiný optický senzor

### Elektronika 
Stále použít RAMPS desku s *** drivery. Možná zkusit 24V verzi? Použil bych výkonější  E3D v6 topné tělísko.

**Comment by kaklik** [comment]
@slimonslimon

**Comment by kaklik** [comment]
Toto Issue jsem rozdělil mezi ostatní zde otevřené.
