### ISSUE TITLE
Protáčení hřídele motoru extruderu

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/RebeliX#9]
Hřídel motoru co podává filament se začala protáčet. A ten motor je úplně horkej
Ani na něm nejde udržet prst.

![47473872_1965259950256928_5619239450048462848_n](https://user-images.githubusercontent.com/1194177/49588436-f5c35600-f966-11e8-83a0-3a748bebe5aa.jpg)
![47498926_321913681965644_175187086029094912_n](https://user-images.githubusercontent.com/1194177/49588437-f6f48300-f966-11e8-977e-fc77c330da5e.jpg)
![47429711_519734838503441_6597366218183671808_n](https://user-images.githubusercontent.com/1194177/49588440-fb20a080-f966-11e8-8917-7566c0d2d895.jpg)
![47503991_925763240942993_716692723008012288_n](https://user-images.githubusercontent.com/1194177/49588445-fe1b9100-f966-11e8-9ab4-fbdd0f8b558e.jpg)

Reportoval @hanuson1

**Comment by kaklik** [comment]
Je potřeba snížit proud buzení motoru, aby byl méně zatěžovaný.  Postup tohoto nastavení je zde: 
https://www.pololu.com/product/1182/faqs

**Comment by roman-dvorak** [comment]
Něco podobného se mi také kdysi stalo. Vzhledem k této konstrukci extruderu s převodem proud lze o dost snížit. A tím se problém podařilo vyřešit.

Já jsem tehdy musel vytisknout nové ozubené kolo, protože původní bylo značně deformované. Také jsem udělal úpravu malého ozubeného kola, že jsem zkrátil část, kde je umístěn šroub tak, aby mezi motorem a ozub. kolem byla větší mezera.

**Comment by kaklik** [comment]
@roman-dvorak je tahle tvoje úprava někde publikovaná?

**Comment by kaklik** [comment]
Proud jsem omezil cca o 60%. Bylo to nastavené na cca 2 ampery přitom max proud podle datasheetu je 1A. Kolečko jsem srovnal s výbrusem a dotáhl šroubek. Tiskne to a už se to nepřehřívá.
To teplo to ale poničilo. Držák motoru je zkroucený a převod už nespoléhá těsně.

![47578909_278004476195583_361175843008937984_n](https://user-images.githubusercontent.com/1194177/49871897-c0f84880-fe17-11e8-9b99-ec7cca66ebc1.jpg)

![47578720_571267236646831_6203324787209535488_n](https://user-images.githubusercontent.com/1194177/49871910-c6ee2980-fe17-11e8-8aa8-13af70d1f645.jpg)

![47494675_2464913473735571_4487935224511987712_n](https://user-images.githubusercontent.com/1194177/49871922-d2415500-fe17-11e8-8440-215140e41e4a.jpg)
